/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/blenderModels/scene.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { VideoTexture, MeshBasicMaterial, DoubleSide } from "three";
import * as THREE from "three";
import videoURL from "/videos/countdownTimer.mp4";
import videoURL2 from "/videos/codingVid.mp4";
import videoURL3 from "/videos/allDimensions.mp4";
export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("./blenderModels/scene.glb");

  //Importing coutDown vid
  const vid = document.createElement("video");
  vid.src = videoURL; // Replace 'your-video-url.mp4' with your video URL
  vid.crossOrigin = "anonymous";
  vid.loop = true;
  vid.muted = true;
  vid.play();
  vid.setAttribute("playsinline", "");

  // Function to handle starting video playback on user interaction
  function startVideoPlayback() {
    vid.play().catch(function (error) {
      // Video playback failed, handle the error here
      console.error("Video playback error:", error);
    });
    document.removeEventListener("touchstart", startVideoPlayback);
  }

  // Attaching the video playback to a user interaction (touchstart)-mobile
  document.addEventListener("touchstart", startVideoPlayback, { once: true });

  const videoTexture = new VideoTexture(vid);
  const videoMaterial = new MeshBasicMaterial({ map: videoTexture });

  //Importing coding vid
  const vid2 = document.createElement("video");
  vid2.src = videoURL2; // Replace 'your-video-url.mp4' with your video URL
  vid2.crossOrigin = "anonymous";
  vid2.loop = true;
  vid2.muted = true;
  vid2.play();
  vid2.setAttribute("playsinline", "");
  // Function to handle starting video playback on user interaction
  function startVideoPlayback2() {
    vid2.play().catch(function (error) {
      // Video playback failed, handle the error here
      console.error("Video playback error:", error);
    });
    document.removeEventListener("touchstart", startVideoPlayback2);
  }

  // Attaching the video playback to a user interaction (touchstart)-mobile
  document.addEventListener("touchstart", startVideoPlayback2, { once: true });

  const videoTexture2 = new VideoTexture(vid2);
  const videoMaterial2 = new MeshBasicMaterial({ map: videoTexture2 });

  //Importing Dimensions vid
  const vid3 = document.createElement("video");
  vid3.src = videoURL3; // Replace 'your-video-url.mp4' with your video URL
  vid3.crossOrigin = "anonymous";
  vid3.loop = true;
  vid3.muted = true;
  vid3.play();
  vid3.setAttribute("playsinline", "");
  // Function to handle starting video playback on user interaction
  function startVideoPlayback3() {
    vid3.play().catch(function (error) {
      // Video playback failed, handle the error here
      console.error("Video playback error:", error);
    });
    document.removeEventListener("touchstart", startVideoPlayback3);
  }

  // Attaching the video playback to a user interaction (touchstart)-mobile
  document.addEventListener("touchstart", startVideoPlayback3, { once: true });

  const videoTexture3 = new VideoTexture(vid3);
  const videoMaterial3 = new MeshBasicMaterial({ map: videoTexture3 });

  // Define the RGB color (in the range [0, 1])
  const rgbColor = new THREE.Color(0, 255, 0); // RGB values are in the range [0, 1]

  // Create a new material with the RGB color
  const rgbMaterial = new THREE.MeshBasicMaterial({ color: rgbColor });

  // code to make the portal Spin
  useFrame(({ scene }) => {
    // Iterate through the children of the scene
    scene.traverse((child) => {
      // Check if the child is a mesh and its name matches "rickPortal"
      if (child.isMesh && child.name === "rickPortal") {
        // Rotate the mesh around the Z-axis by a small angle in each frame
        child.rotation.x += 0.01; // You can adjust the rotation speed as needed
      }
    });
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={5}>
        <mesh
          geometry={nodes.Plane002.geometry}
          material={materials.floorColor}
        />
        <mesh
          geometry={nodes.Plane002_1.geometry}
          material={materials.wallColor}
        />
        <mesh
          geometry={nodes.Plane002_2.geometry}
          material={materials.bottomColor}
        />
        <mesh
          geometry={nodes.Plane002_3.geometry}
          material={materials.outColor}
        />
      </group>
      <group
        position={[-1.947, 1.373, 3.06]}
        rotation={[-1.585, 0.606, -1.567]}
        scale={[0.265, 0.37, 0.036]}
      >
        <mesh
          geometry={nodes.Cube026.geometry}
          material={materials.bookFrame}
        />
        <mesh
          geometry={nodes.Cube026_1.geometry}
          material={materials["Material.036"]}
        />
        <mesh
          geometry={nodes.Cube026_2.geometry}
          material={materials.crackingCodeCover}
        />
      </group>
      <group
        position={[-0.385, 3.433, -0.584]}
        rotation={[-1.161, -0.024, -0.043]}
        scale={[0.634, 0.951, 0.46]}
      >
        <mesh
          geometry={nodes.Plane015.geometry}
          material={materials["Material.034"]}
        />
        <mesh
          geometry={nodes.Plane015_1.geometry}
          material={materials["Material.026"]}
        />
        <mesh
          geometry={nodes.Plane015_2.geometry}
          material={materials["Material.019"]}
        />
        <mesh
          geometry={nodes.Plane015_3.geometry}
          material={materials["Material.027"]}
        />
        <mesh
          geometry={nodes.Plane015_4.geometry}
          material={materials["Material.016"]}
        />
        <mesh
          geometry={nodes.Plane015_5.geometry}
          material={materials["Material.018"]}
        />
        <mesh
          geometry={nodes.Plane015_6.geometry}
          material={materials["Material.024"]}
        />
        <mesh
          geometry={nodes.Plane015_7.geometry}
          material={materials["Material.025"]}
        />
        <mesh
          geometry={nodes.Plane015_8.geometry}
          material={materials["Material.030"]}
        />
        <mesh
          geometry={nodes.Plane015_9.geometry}
          material={materials["Material.028"]}
        />
        <mesh
          geometry={nodes.Plane015_10.geometry}
          material={materials["Material.033"]}
        />
        <mesh
          geometry={nodes.Plane015_11.geometry}
          material={materials["Material.020"]}
        />
        <mesh
          geometry={nodes.Plane015_12.geometry}
          material={materials["Material.032"]}
        />
        <mesh
          geometry={nodes.Plane015_13.geometry}
          material={materials["Material.031"]}
        />
        <mesh
          geometry={nodes.Plane015_14.geometry}
          material={materials["Material.022"]}
        />
        <mesh
          geometry={nodes.Plane015_15.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          geometry={nodes.Plane015_16.geometry}
          material={materials["Material.023"]}
        />
        <mesh
          geometry={nodes.Plane015_17.geometry}
          material={materials["Material.021"]}
        />
        <mesh
          geometry={nodes.Plane015_18.geometry}
          material={materials["Material.029"]}
        />
      </group>
      <group position={[0.947, 2.188, 0.765]} scale={[0.524, 0.743, 0.691]}>
        <mesh
          geometry={nodes.Cube002.geometry}
          material={materials["Material.014"]}
        />
        <mesh
          geometry={nodes.Cube002_1.geometry}
          material={materials["Material.015"]}
        />
        <mesh
          geometry={nodes.Cube002_2.geometry}
          material={materials["Material.242"]}
        />
        <mesh
          geometry={nodes.Cube002_3.geometry}
          material={materials["Material.243"]}
        />
        <mesh
          geometry={nodes.Cube002_4.geometry}
          material={materials["Material.244"]}
        />
        <mesh
          geometry={nodes.Cube002_5.geometry}
          material={materials["Material.245"]}
        />
        <mesh
          geometry={nodes.Cube002_6.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Cube002_7.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Cube002_8.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          geometry={nodes.Cube002_9.geometry}
          material={materials["Material.013"]}
        />
        <mesh
          geometry={nodes.Cube002_10.geometry}
          material={materials["Material.012"]}
        />
        <mesh
          geometry={nodes.Cube002_11.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          geometry={nodes.Cube002_12.geometry}
          material={materials["Material.011"]}
        />
        <mesh
          geometry={nodes.Cube002_13.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          geometry={nodes.Cube002_14.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          geometry={nodes.Cube002_15.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          geometry={nodes.Cube002_16.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube002_17.geometry}
          material={materials["Material.003"]}
        />
      </group>
      <group position={[-4.363, 1.759, 4.452]} scale={[0.274, 0.36, 0.051]}>
        <mesh
          geometry={nodes.Cube008.geometry}
          material={materials["Material.039"]}
        />
        <mesh
          geometry={nodes.Cube008_1.geometry}
          material={materials["Material.040"]}
        />
      </group>
      <group position={[-4.363, 1.761, 4.324]} scale={[0.274, 0.36, 0.051]}>
        <mesh
          geometry={nodes.Cube009.geometry}
          material={materials["Material.041"]}
        />
        <mesh
          geometry={nodes.Cube009_1.geometry}
          material={materials["Material.042"]}
        />
      </group>
      <group position={[-4.363, 1.752, 4.19]} scale={[0.274, 0.36, 0.051]}>
        <mesh
          geometry={nodes.Cube010.geometry}
          material={materials["Material.043"]}
        />
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials["Material.044"]}
        />
      </group>
      <group position={[-4.356, 1.806, 4.034]} scale={[0.274, 0.418, 0.051]}>
        <mesh
          geometry={nodes.Cube011.geometry}
          material={materials["Material.045"]}
        />
        <mesh
          geometry={nodes.Cube011_1.geometry}
          material={materials["Material.046"]}
        />
      </group>
      <group
        position={[-4.363, 1.752, 3.795]}
        rotation={[0.422, 0, 0]}
        scale={[0.274, 0.36, 0.051]}
      >
        <mesh
          geometry={nodes.Cube012.geometry}
          material={materials["Material.047"]}
        />
        <mesh
          geometry={nodes.Cube012_1.geometry}
          material={materials["Material.048"]}
        />
      </group>
      <group
        position={[-4.289, 1.461, 2.939]}
        rotation={[-1.525, -0.004, -2.853]}
        scale={[0.274, 0.418, 0.051]}
      >
        <mesh
          geometry={nodes.Cube013.geometry}
          material={materials["Material.053"]}
        />
        <mesh
          geometry={nodes.Cube013_1.geometry}
          material={materials["Material.054"]}
        />
        <mesh
          geometry={nodes.Cube013_2.geometry}
          material={materials.dataIntenseCover}
        />
      </group>
      <group position={[-4.356, 1.806, 3.51]} scale={[0.274, 0.418, 0.051]}>
        <mesh
          geometry={nodes.Cube014.geometry}
          material={materials["Material.049"]}
        />
        <mesh
          geometry={nodes.Cube014_1.geometry}
          material={materials["Material.050"]}
        />
      </group>
      <group
        position={[-4.356, 0.633, 4.478]}
        rotation={[0.286, 0, 0]}
        scale={[0.274, 0.325, 0.051]}
      >
        <mesh
          geometry={nodes.Cube015.geometry}
          material={materials["Material.055"]}
        />
        <mesh
          geometry={nodes.Cube015_1.geometry}
          material={materials["Material.056"]}
        />
      </group>
      <group
        position={[-4.31, 0.542, 4.298]}
        rotation={[0.514, 0.039, 0.059]}
        scale={[0.229, 0.244, 0.051]}
      >
        <mesh
          geometry={nodes.Cube016.geometry}
          material={materials["Material.057"]}
        />
        <mesh
          geometry={nodes.Cube016_1.geometry}
          material={materials["Material.058"]}
        />
      </group>
      <group
        position={[-4.279, 0.47, 4.105]}
        rotation={[0.701, 0.039, 0.059]}
        scale={[0.168, 0.194, 0.048]}
      >
        <mesh
          geometry={nodes.Cube017.geometry}
          material={materials["Material.059"]}
        />
        <mesh
          geometry={nodes.Cube017_1.geometry}
          material={materials["Material.060"]}
        />
      </group>
      <group position={[-4.356, 0.695, 3.861]} scale={[0.274, 0.369, 0.051]}>
        <mesh
          geometry={nodes.Cube005.geometry}
          material={materials["Material.061"]}
        />
        <mesh
          geometry={nodes.Cube005_1.geometry}
          material={materials["Material.062"]}
        />
      </group>
      <group position={[-4.356, 0.695, 3.719]} scale={[0.274, 0.369, 0.051]}>
        <mesh
          geometry={nodes.Cube018.geometry}
          material={materials["Material.063"]}
        />
        <mesh
          geometry={nodes.Cube018_1.geometry}
          material={materials["Material.064"]}
        />
      </group>
      <group position={[-4.356, 0.579, 3.573]} scale={[0.274, 0.26, 0.051]}>
        <mesh
          geometry={nodes.Cube019.geometry}
          material={materials["Material.065"]}
        />
        <mesh
          geometry={nodes.Cube019_1.geometry}
          material={materials["Material.066"]}
        />
      </group>
      <group position={[-4.356, 0.695, 3.431]} scale={[0.274, 0.369, 0.051]}>
        <mesh
          geometry={nodes.Cube020.geometry}
          material={materials["Material.067"]}
        />
        <mesh
          geometry={nodes.Cube020_1.geometry}
          material={materials["Material.068"]}
        />
      </group>
      <group position={[-4.356, 0.695, 3.273]} scale={[0.274, 0.369, 0.051]}>
        <mesh
          geometry={nodes.Cube021.geometry}
          material={materials["Material.069"]}
        />
        <mesh
          geometry={nodes.Cube021_1.geometry}
          material={materials["Material.070"]}
        />
      </group>
      <group position={[-4.356, 0.695, 3.098]} scale={[0.274, 0.369, 0.051]}>
        <mesh
          geometry={nodes.Cube022.geometry}
          material={materials["Material.071"]}
        />
        <mesh
          geometry={nodes.Cube022_1.geometry}
          material={materials["Material.072"]}
        />
      </group>
      <group position={[-4.356, 0.579, 2.925]} scale={[0.274, 0.26, 0.051]}>
        <mesh
          geometry={nodes.Cube023.geometry}
          material={materials["Material.073"]}
        />
        <mesh
          geometry={nodes.Cube023_1.geometry}
          material={materials["Material.074"]}
        />
      </group>
      <group
        position={[-4.356, 0.542, 2.688]}
        rotation={[-0.603, 0, 0]}
        scale={[0.274, 0.22, 0.046]}
      >
        <mesh
          geometry={nodes.Cube024.geometry}
          material={materials["Material.075"]}
        />
        <mesh
          geometry={nodes.Cube024_1.geometry}
          material={materials["Material.076"]}
        />
      </group>
      <group
        position={[-4.356, 0.497, 2.527]}
        rotation={[-0.375, 0, 0]}
        scale={[0.274, 0.183, 0.046]}
      >
        <mesh
          geometry={nodes.Cube025.geometry}
          material={materials["Material.077"]}
        />
        <mesh
          geometry={nodes.Cube025_1.geometry}
          material={materials["Material.078"]}
        />
      </group>
      <group
        position={[1.531, 2.357, -3.932]}
        rotation={[1.625, -0.148, 0.142]}
        scale={[0.019, 0.01, 0.018]}
      >
        <mesh
          geometry={nodes.Cylinder003.geometry}
          material={materials["Material.079"]}
        />
        <mesh
          geometry={nodes.Cylinder003_1.geometry}
          material={materials["Material.080"]}
        />
        <mesh
          geometry={nodes.Cylinder003_2.geometry}
          material={materials["Material.081"]}
        />
        <mesh
          geometry={nodes.Cylinder003_3.geometry}
          material={materials["Material.082"]}
        />
        <mesh
          geometry={nodes.Cylinder003_4.geometry}
          material={materials["Material.083"]}
        />
        <mesh
          geometry={nodes.Cylinder003_5.geometry}
          material={materials["Material.084"]}
        />
        <mesh
          geometry={nodes.Cylinder003_6.geometry}
          material={materials["Material.085"]}
        />
        <mesh
          geometry={nodes.Cylinder003_7.geometry}
          material={materials["Material.086"]}
        />
        <mesh
          geometry={nodes.Cylinder003_8.geometry}
          material={materials["Material.087"]}
        />
        <mesh
          geometry={nodes.Cylinder003_9.geometry}
          material={materials["Material.088"]}
        />
        <mesh
          geometry={nodes.Cylinder003_10.geometry}
          material={materials["Material.089"]}
        />
        <mesh
          geometry={nodes.Cylinder003_11.geometry}
          material={materials["Material.090"]}
        />
        <mesh
          geometry={nodes.Cylinder003_12.geometry}
          material={materials["Material.091"]}
        />
        <mesh
          geometry={nodes.Cylinder003_13.geometry}
          material={materials["Material.092"]}
        />
        <mesh
          geometry={nodes.Cylinder003_14.geometry}
          material={materials["Material.093"]}
        />
      </group>
      <group position={[1.389, 0.894, -3.982]} scale={[0.264, 0.436, 0.617]}>
        <mesh
          geometry={nodes.Cube.geometry}
          material={materials["Material.094"]}
        />
        <mesh
          geometry={nodes.Cube_1.geometry}
          material={materials["Material.095"]}
        />
        <mesh
          geometry={nodes.Cube_2.geometry}
          material={materials["Material.096"]}
        />
        <mesh
          geometry={nodes.Cube_3.geometry}
          material={materials["Material.097"]}
        />
        <mesh
          geometry={nodes.Cube_4.geometry}
          material={materials["Material.098"]}
        />
        <mesh
          geometry={nodes.Cube_5.geometry}
          material={materials["Material.099"]}
        />
      </group>
      <group position={[-0.249, 2.077, -3.355]} scale={[0.332, 1.077, 0.229]}>
        <mesh
          geometry={nodes.Plane003.geometry}
          material={materials["Material.100"]}
        />
        <mesh
          geometry={nodes.Plane003_1.geometry}
          material={materials["Material.101"]}
        />
        <mesh
          geometry={nodes.Plane003_2.geometry}
          material={materials["Material.102"]}
        />
      </group>
      <group
        position={[-0.246, 2.104, -4.611]}
        rotation={[-0.036, -0.009, -0.009]}
        scale={[0.086, 0.058, 0.169]}
      >
        <mesh
          geometry={nodes.Plane.geometry}
          material={materials["Material.103"]}
        />
        <mesh
          geometry={nodes.Plane_1.geometry}
          material={materials["Material.104"]}
        />
      </group>
      <group position={[0.338, 2.076, -3.321]} scale={[0.061, 1.794, 0.104]}>
        <mesh
          geometry={nodes.Plane005.geometry}
          material={materials["Material.105"]}
        />
        <mesh
          geometry={nodes.Plane005_1.geometry}
          material={materials["Material.106"]}
        />
      </group>
      <group position={[1.603, 2.205, -4.542]} scale={[-0.078, 0.065, 0.07]}>
        <mesh
          geometry={nodes.Cube001.geometry}
          material={materials["Material.157"]}
        />
        <mesh
          geometry={nodes.Cube001_1.geometry}
          material={materials["Material.161"]}
        />
        <mesh
          geometry={nodes.Cube001_2.geometry}
          material={materials["Material.162"]}
        />
        <mesh
          geometry={nodes.Cube001_3.geometry}
          material={materials["Material.165"]}
        />
        <mesh
          geometry={nodes.Cube001_4.geometry}
          material={materials["Material.159"]}
        />
        <mesh
          geometry={nodes.Cube001_5.geometry}
          material={materials["Material.160"]}
        />
        <mesh
          geometry={nodes.Cube001_6.geometry}
          material={materials["Material.163"]}
        />
        <mesh
          geometry={nodes.Cube001_7.geometry}
          material={materials["Material.164"]}
        />
        <mesh
          geometry={nodes.Cube001_8.geometry}
          material={materials["Material.158"]}
        />
      </group>
      <group
        position={[-1.375, 2.116, -3.992]}
        rotation={[-0.107, -1.235, 1.46]}
        scale={[0.023, 0.16, 0.015]}
      >
        <mesh
          geometry={nodes.Plane142.geometry}
          material={materials.Material}
        />
        <mesh
          geometry={nodes.Plane142_1.geometry}
          material={materials["Material.144"]}
        />
        <mesh
          geometry={nodes.Plane142_2.geometry}
          material={materials["Material.142"]}
        />
        <mesh
          geometry={nodes.Plane142_3.geometry}
          material={materials["Material.143"]}
        />
        <mesh
          geometry={nodes.Plane142_4.geometry}
          material={materials["Material.137"]}
        />
        <mesh
          geometry={nodes.Plane142_5.geometry}
          material={materials["Material.141"]}
        />
        <mesh
          geometry={nodes.Plane142_6.geometry}
          material={materials["Material.138"]}
        />
        <mesh
          geometry={nodes.Plane142_7.geometry}
          material={materials["Material.136"]}
        />
        <mesh
          geometry={nodes.Plane142_8.geometry}
          material={materials["Material.140"]}
        />
        <mesh
          geometry={nodes.Plane142_9.geometry}
          material={materials["Material.108"]}
        />
        <mesh
          geometry={nodes.Plane142_10.geometry}
          material={materials["Material.052"]}
        />
        <mesh
          geometry={nodes.Plane142_11.geometry}
          material={materials["Material.107"]}
        />
        <mesh
          geometry={nodes.Plane142_12.geometry}
          material={materials["Material.109"]}
        />
        <mesh
          geometry={nodes.Plane142_13.geometry}
          material={materials["Material.110"]}
        />
        <mesh
          geometry={nodes.Plane142_14.geometry}
          material={materials["Material.111"]}
        />
        <mesh
          geometry={nodes.Plane142_15.geometry}
          material={materials["Material.112"]}
        />
        <mesh
          geometry={nodes.Plane142_16.geometry}
          material={materials["Material.113"]}
        />
        <mesh
          geometry={nodes.Plane142_17.geometry}
          material={materials["Material.115"]}
        />
        <mesh
          geometry={nodes.Plane142_18.geometry}
          material={materials["Material.114"]}
        />
        <mesh
          geometry={nodes.Plane142_19.geometry}
          material={materials["Material.126"]}
        />
        <mesh
          geometry={nodes.Plane142_20.geometry}
          material={materials["Material.128"]}
        />
        <mesh
          geometry={nodes.Plane142_21.geometry}
          material={materials["Material.132"]}
        />
        <mesh
          geometry={nodes.Plane142_22.geometry}
          material={materials["Material.133"]}
        />
        <mesh
          geometry={nodes.Plane142_23.geometry}
          material={materials["Material.135"]}
        />
        <mesh
          geometry={nodes.Plane142_24.geometry}
          material={materials["Material.134"]}
        />
        <mesh
          geometry={nodes.Plane142_25.geometry}
          material={materials["Material.117"]}
        />
        <mesh
          geometry={nodes.Plane142_26.geometry}
          material={materials["Material.131"]}
        />
        <mesh
          geometry={nodes.Plane142_27.geometry}
          material={materials["Material.129"]}
        />
        <mesh
          geometry={nodes.Plane142_28.geometry}
          material={materials["Material.130"]}
        />
        <mesh
          geometry={nodes.Plane142_29.geometry}
          material={materials["Material.116"]}
        />
        <mesh
          geometry={nodes.Plane142_30.geometry}
          material={materials["Material.127"]}
        />
        <mesh
          geometry={nodes.Plane142_31.geometry}
          material={materials["Material.118"]}
        />
        <mesh
          geometry={nodes.Plane142_32.geometry}
          material={materials["Material.119"]}
        />
        <mesh
          geometry={nodes.Plane142_33.geometry}
          material={materials["Material.120"]}
        />
        <mesh
          geometry={nodes.Plane142_34.geometry}
          material={materials["Material.121"]}
        />
        <mesh
          geometry={nodes.Plane142_35.geometry}
          material={materials["Material.124"]}
        />
        <mesh
          geometry={nodes.Plane142_36.geometry}
          material={materials["Material.122"]}
        />
        <mesh
          geometry={nodes.Plane142_37.geometry}
          material={materials["Material.125"]}
        />
        <mesh
          geometry={nodes.Plane142_38.geometry}
          material={materials["Material.123"]}
        />
        <mesh
          geometry={nodes.Plane142_39.geometry}
          material={materials["Material.156"]}
        />
        <mesh
          geometry={nodes.Plane142_40.geometry}
          material={materials["Material.154"]}
        />
        <mesh
          geometry={nodes.Plane142_41.geometry}
          material={materials["Material.155"]}
        />
        <mesh
          geometry={nodes.Plane142_42.geometry}
          material={materials["Material.148"]}
        />
        <mesh
          geometry={nodes.Plane142_43.geometry}
          material={materials["Material.147"]}
        />
        <mesh
          geometry={nodes.Plane142_44.geometry}
          material={materials["Material.145"]}
        />
        <mesh
          geometry={nodes.Plane142_45.geometry}
          material={materials["Material.151"]}
        />
        <mesh
          geometry={nodes.Plane142_46.geometry}
          material={materials["Material.149"]}
        />
        <mesh
          geometry={nodes.Plane142_47.geometry}
          material={materials["Material.150"]}
        />
        <mesh
          geometry={nodes.Plane142_48.geometry}
          material={materials["Material.152"]}
        />
        <mesh
          geometry={nodes.Plane142_49.geometry}
          material={materials["Material.153"]}
        />
        <mesh
          geometry={nodes.Plane142_50.geometry}
          material={materials["Material.146"]}
        />
        <mesh
          geometry={nodes.Plane142_51.geometry}
          material={materials["Material.139"]}
        />
      </group>
      <group
        position={[-4.439, 2.925, 2.342]}
        rotation={[-1.582, -0.001, -0.001]}
        scale={[0.023, 0.013, 0.023]}
      >
        <mesh
          geometry={nodes.Cylinder006.geometry}
          material={materials["Material.167"]}
        />
        <mesh
          geometry={nodes.Cylinder006_1.geometry}
          material={materials["Material.173"]}
        />
        <mesh
          geometry={nodes.Cylinder006_2.geometry}
          material={materials["Material.176"]}
        />
        <mesh
          geometry={nodes.Cylinder006_3.geometry}
          material={materials["Material.172"]}
        />
        <mesh
          geometry={nodes.Cylinder006_4.geometry}
          material={materials["Material.170"]}
        />
        <mesh
          geometry={nodes.Cylinder006_5.geometry}
          material={materials["Material.171"]}
        />
        <mesh
          geometry={nodes.Cylinder006_6.geometry}
          material={materials["Material.168"]}
        />
        <mesh
          geometry={nodes.Cylinder006_7.geometry}
          material={materials["Material.169"]}
        />
        <mesh
          geometry={nodes.Cylinder006_8.geometry}
          material={materials["Material.174"]}
        />
        <mesh
          geometry={nodes.Cylinder006_9.geometry}
          material={materials["Material.177"]}
        />
        <mesh
          geometry={nodes.Cylinder006_10.geometry}
          material={materials["Material.175"]}
        />
        <mesh
          geometry={nodes.Cylinder006_11.geometry}
          material={materials["Material.178"]}
        />
      </group>
      <group position={[3.316, 1.489, -4.011]} scale={[0.285, 0.036, 0.263]}>
        <mesh
          geometry={nodes.Cube007.geometry}
          material={materials["Material.189"]}
        />
        <mesh
          geometry={nodes.Cube007_1.geometry}
          material={materials["Material.190"]}
        />
      </group>
      <group
        position={[3.495, 2.788, -4.054]}
        rotation={[0.085, -0.144, -1.711]}
        scale={[0.257, 0.251, 0.324]}
      >
        <mesh
          geometry={nodes.Plane028.geometry}
          material={materials["Material.180"]}
        />
        <mesh
          geometry={nodes.Plane028_1.geometry}
          material={materials["Material.183"]}
        />
        <mesh
          geometry={nodes.Plane028_2.geometry}
          material={materials["Material.184"]}
        />
        <mesh
          geometry={nodes.Plane028_3.geometry}
          material={materials["Material.185"]}
        />
        <mesh
          geometry={nodes.Plane028_4.geometry}
          material={materials["Material.186"]}
        />
        <mesh
          geometry={nodes.Plane028_5.geometry}
          material={materials["Material.187"]}
        />
        <mesh
          geometry={nodes.Plane028_6.geometry}
          // material={materials["Material.188"]}
        >
          <meshBasicMaterial color={"rgb(17, 228, 138)"} />
        </mesh>
      </group>
      <group position={[-3.448, 1.016, -3.682]} scale={[0.441, 0.396, 0.382]}>
        <mesh
          geometry={nodes.Cube004.geometry}
          material={materials["Material.198"]}
        />
        <mesh
          geometry={nodes.Cube004_1.geometry}
          // material={materials["Material.199"]}
        >
          {" "}
          <meshBasicMaterial color={"rgb(35, 255, 255)"} />
        </mesh>
        <mesh
          geometry={nodes.Cube004_2.geometry}
          material={materials["Material.200"]}
        />
        <mesh
          geometry={nodes.Cube004_3.geometry}
          material={materials["Material.201"]}
        />
        <mesh
          geometry={nodes.Cube004_4.geometry}
          material={materials["Material.202"]}
        />
        <mesh
          geometry={nodes.Cube004_5.geometry}
          // material={materials["Material.203"]}
        >
          {" "}
          <meshBasicMaterial color={"rgb(35, 255, 255)"} />
        </mesh>
      </group>
      <group
        position={[-4.184, 2.769, -3.913]}
        rotation={[0, 0, 1.555]}
        scale={[0.538, 0.102, 0.562]}
      >
        <mesh
          geometry={nodes.Cylinder008.geometry}
          material={materials["Material.204"]}
        />
        <mesh
          geometry={nodes.Cylinder008_1.geometry}
          material={materials["Material.205"]}
        />
        <mesh
          geometry={nodes.Cylinder008_2.geometry}
          material={materials["Material.206"]}
        />
        <mesh
          geometry={nodes.Cylinder008_3.geometry}
          material={materials["Material.207"]}
        />
        <mesh
          geometry={nodes.Cylinder008_4.geometry}
          material={materials.tempGauge}
        />
        <mesh
          geometry={nodes.Cylinder008_5.geometry}
          material={materials["Material.208"]}
        />
        <mesh
          geometry={nodes.Cylinder008_6.geometry}
          material={materials["Material.209"]}
        />
      </group>
      <group position={[-3.578, 2.122, -3.922]} scale={[1.156, 0.108, 0.972]}>
        <mesh
          geometry={nodes.Cube029.geometry}
          material={materials["Material.192"]}
        />
        <mesh
          geometry={nodes.Cube029_1.geometry}
          material={materials["Material.193"]}
        />
        <mesh
          geometry={nodes.Cube029_2.geometry}
          material={materials["Material.194"]}
        />
        <mesh
          geometry={nodes.Cube029_3.geometry}
          material={materials["Material.195"]}
        />
        <mesh
          geometry={nodes.Cube029_4.geometry}
          material={materials["Material.196"]}
        />
        <mesh
          geometry={nodes.Cube029_5.geometry}
          material={materials["Material.197"]}
        />
        <mesh
          geometry={nodes.Cube029_6.geometry}
          material={materials["Material.221"]}
        />
      </group>
      <group
        position={[-4.411, 3.967, 4.518]}
        rotation={[0.472, 0.063, 1.582]}
        scale={[0.282, 1.302, 0.387]}
      >
        <mesh
          geometry={nodes.BezierCircle.geometry}
          material={materials["Material.211"]}
        />
        <mesh
          geometry={nodes.BezierCircle_1.geometry}
          material={materials["Material.212"]}
        />
        <mesh
          geometry={nodes.BezierCircle_2.geometry}
          material={materials["Material.213"]}
        />
        <mesh
          geometry={nodes.BezierCircle_3.geometry}
          material={materials["Material.214"]}
        />
      </group>
      <group
        position={[-4.978, 4.829, -2.984]}
        rotation={[-0.008, -0.013, 3.141]}
        scale={[0.148, 0.284, 0.287]}
      >
        <mesh
          geometry={nodes.Plane004.geometry}
          material={materials["Material.216"]}
        />
        <mesh
          geometry={nodes.Plane004_1.geometry}
          material={materials["rick&mortyPainting"]}
        />
      </group>
      <group
        position={[2.646, 4.666, -4.961]}
        rotation={[-2.657, -1.552, 0.486]}
        scale={[0.148, 0.284, 0.427]}
      >
        <mesh
          geometry={nodes.Plane010.geometry}
          material={materials["Material.217"]}
        />
        <mesh
          geometry={nodes.Plane010_1.geometry}
          material={materials.banksyArt}
        />
      </group>
      <group
        position={[-4.978, 4.765, 4.058]}
        rotation={[-0.011, -0.003, -3.132]}
        scale={[0.148, 0.284, 0.287]}
      >
        <mesh
          geometry={nodes.Plane011.geometry}
          material={materials["Material.215"]}
        />
        <mesh
          geometry={nodes.Plane011_1.geometry}
          material={materials.fatThor}
        />
      </group>
      <group
        position={[-4.509, 0.289, -2.217]}
        rotation={[Math.PI, 0.042, 1.557]}
        scale={[0.283, 1, 0.31]}
      >
        <mesh
          geometry={nodes.Plane285.geometry}
          material={materials["Material.218"]}
        />
        <mesh
          geometry={nodes.Plane285_1.geometry}
          material={materials["Material.241"]}
        />
        <mesh
          geometry={nodes.Plane285_2.geometry}
          material={materials["Material.222"]}
        />
        <mesh
          geometry={nodes.Plane285_3.geometry}
          material={materials["Material.223"]}
        />
        <mesh
          geometry={nodes.Plane285_4.geometry}
          material={materials["Material.224"]}
        />
        <mesh
          geometry={nodes.Plane285_5.geometry}
          material={materials["Material.225"]}
        />
        <mesh
          geometry={nodes.Plane285_6.geometry}
          material={materials["Material.226"]}
        />
        <mesh
          geometry={nodes.Plane285_7.geometry}
          material={materials["Material.229"]}
        />
        <mesh
          geometry={nodes.Plane285_8.geometry}
          material={materials["Material.228"]}
        />
        <mesh
          geometry={nodes.Plane285_9.geometry}
          material={materials["Material.227"]}
        />
        <mesh
          geometry={nodes.Plane285_10.geometry}
          material={materials["Material.230"]}
        />
        <mesh
          geometry={nodes.Plane285_11.geometry}
          material={materials["Material.231"]}
        />
        <mesh
          geometry={nodes.Plane285_12.geometry}
          material={materials["Material.232"]}
        />
        <mesh
          geometry={nodes.Plane285_13.geometry}
          material={materials["Material.233"]}
        />
        <mesh
          geometry={nodes.Plane285_14.geometry}
          material={materials["Material.234"]}
        />
        <mesh
          geometry={nodes.Plane285_15.geometry}
          material={materials["Material.235"]}
        />
        <mesh
          geometry={nodes.Plane285_16.geometry}
          material={materials["Material.236"]}
        />
        <mesh
          geometry={nodes.Plane285_17.geometry}
          material={materials["Material.237"]}
        />
        <mesh
          geometry={nodes.Plane285_18.geometry}
          material={materials["Material.238"]}
        />
        <mesh
          geometry={nodes.Plane285_19.geometry}
          material={materials["Material.240"]}
        />
        <mesh
          geometry={nodes.Plane285_20.geometry}
          material={materials["Material.219"]}
        />
        <mesh
          geometry={nodes.Plane285_21.geometry}
          material={materials["Material.220"]}
        />
        <mesh
          geometry={nodes.Plane285_22.geometry}
          material={materials["Material.239"]}
        />
      </group>
      <mesh
        geometry={nodes.couch.geometry}
        material={materials["Material.035"]}
        position={[-2.257, 1.088, 3.157]}
        scale={[0.258, 2.093, 1.183]}
      />
      <mesh
        geometry={nodes.desk.geometry}
        material={materials["Material.037"]}
        position={[-0.038, 0.434, -4.715]}
        rotation={[-1.572, 0, 3.139]}
        scale={[1.82, 1, 0.137]}
      />
      <mesh
        geometry={nodes.winFrame.geometry}
        material={materials["Material.017"]}
        position={[-0.001, 3.497, -5.216]}
        rotation={[1.571, -0.007, -0.002]}
        scale={[2.183, 1.001, 1.256]}
      />
      <mesh
        geometry={nodes.bookShelf.geometry}
        material={materials["Material.038"]}
        position={[-4.493, 0.064, 3.516]}
        scale={[0.474, 0.041, 1.33]}
      />
      <mesh
        geometry={nodes.mousePad.geometry}
        material={materials["Material.072"]}
        position={[0.337, 2.069, -3.319]}
        rotation={[-0.002, -0.005, -0.018]}
        scale={[0.183, 1, 0.161]}
      />
      <mesh
        geometry={nodes.plantCoaster.geometry}
        material={materials["Material.051"]}
        position={[1.6, 2.056, -4.563]}
        scale={[0.145, 0.406, 0.18]}
      />
      <mesh
        geometry={nodes.portalStand.geometry}
        material={materials["Material.166"]}
        position={[-4.516, 2.697, 2.775]}
        rotation={[-1.566, 0, 0]}
      />
      <mesh
        geometry={nodes.couchTable.geometry}
        material={materials["Material.182"]}
        position={[3.873, 1.396, 3.206]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.479, 0.059, 0.512]}
      />
      <mesh
        geometry={nodes.helmetStand.geometry}
        material={materials["Material.181"]}
        position={[3.876, 1.468, 3.209]}
        scale={[0.217, 0.014, 0.222]}
      />
      <mesh
        geometry={nodes.lokiHelmet.geometry}
        material={materials["Material.179"]}
        position={[3.864, 2.448, 3.637]}
        rotation={[-3.141, 1.57, -1.615]}
        scale={[0.817, 0.835, 0.908]}
      />
      <mesh
        geometry={nodes.littleTable.geometry}
        material={materials["Material.191"]}
        position={[3.312, 1.395, -4.015]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.517, 0.054, 0.533]}
      />
      <mesh
        geometry={nodes.rockPile.geometry}
        material={materials["Material.210"]}
        position={[-4.442, 2.565, 4.43]}
        rotation={[1.392, -0.147, -1.003]}
        scale={[0.325, 0.396, 0.261]}
      />
      <mesh
        name="rickPortal"
        geometry={nodes.rickPortal.geometry}
        material={materials["Material.250"]}
        position={[-4.639, 2.129, -0.276]}
        rotation={[0, 0, -1.564]}
        scale={[2.436, 1.638, 2.634]}
      />
      <mesh
        geometry={nodes.countDown.geometry}
        // material={materials["Material.247"]}
        material={videoMaterial}
        position={[-3.633, 3.385, -3.802]}
        // rotation={[1.213, -0.016, 0.002]}
        rotation={[1.213, Math.PI, Math.PI]}
        scale={[0.146, 0.982, 0.093]}
        material-side={DoubleSide}
      />
      <mesh
        geometry={nodes.dimVid.geometry}
        // material={materials["Material.248"]}
        material={videoMaterial3}
        position={[-4.505, 4.397, -0.097]}
        // rotation={[1.579, -0.001, -1.554]}
        rotation={[-1.579, -0.001, -1.554]}
        scale={[0.436, 1, 0.448]}
        // material-side={DoubleSide}
      />
      <mesh
        geometry={nodes.laptopVid.geometry}
        // material={materials["Material.246"]}
        material={videoMaterial2}
        position={[-0.248, 2.311, -3.608]}
        // rotation={[1.362, -0.002, 0.008]}
        rotation={[1.362, Math.PI, Math.PI]}
        scale={[0.312, 0.993, 0.193]}
        material-side={DoubleSide}
      />
      <mesh
        geometry={nodes.monVud.geometry}
        // material={materials["Material.246"]}
        material={videoMaterial2}
        position={[-0.206, 3.4, -4.219]}
        // rotation={[1.544, -0.002, 0.008]}
        rotation={[-1.6, 0.004, -0.008]}
        scale={[1.563, 1, 0.711]}
        // material-side={DoubleSide}
      />
    </group>
  );
}

useGLTF.preload("/scene.glb");
